apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "weather-app.name" . }}