replicaCount: 1

image:
  repository: pathums/weatherapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001
#  nodePort: 30001

env:
  WEATHER_API_KEY: ""

#ingress configuration

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: weather.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: weather-local-tls
      hosts: 
        - weather.local


    